exports.MessageTypes = {
    APPEND_ENTRIES: 'APPEND_ENTRIES',
    CONFIRM_ENTRIES: 'CONFIRM_ENTRIES',
    REQUEST_VOTE: 'REQUEST_VOTE' ,
    VOTE: 'VOTE',
    TIMEOUT_NOW: 'TIMEOUT_NOW'
};
exports.Roles = {
    LEADER: 'LEADER',
    FOLLOWER: 'FOLLOWER',
    CANDIDATE: 'CANDIDATE'
};

exports.Settings= {
    TIMEOUT_WINDOW: 300,
    MIN_TIMEOUT : 150,
    APPEND_INTERVAL: 75,
    NETWORK_DELAY_MEDIAN: 20,
    NETWORK_DELAY_STD_DEVIATION: 2
};