exports.MessageTypes = {
    APPEND_ENTRIES: 'APPEND_ENTRIES',
    CONFIRM_ENTRIES: 'CONFIRM_ENTRIES',
    REQUEST_VOTE: 'REQUEST_VOTE' ,
    VOTE: 'VOTE'


};
exports.Roles = {
    LEADER: 'LEADER',
    FOLLOWER: 'FOLLOWER',
    CANDIDATE: 'CANDIDATE'
};

exports.Settings= {
    TIMEOUT_WINDOW: 5000,
    MIN_TIMEOUT : 2000,
    APPEND_INTERVAL: 1000
};